# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "rust-perceptron-arr"
version = "0.1.0"
authors = ["Nick Blantz <nicholasblantz@gmail.com>", "Scott Miller", "Ryan Matthews"]
edition = "2018"

[dependencies]
rand = "0.7"
